export const CREATE_USER = 'CREATE_USER';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const GET_MESSAGE = 'GET_MESSAGE';

export const USER_TYPING = 'USER_TYPING';
export const USER_STOP_TYPING = 'USER_STOP_TYPING';
export const USER_ACTION_MESSAGE = 'USER_ACTION_MESSAGE';
export const CLEAR_USER_ACTION_MESSAGE = 'CLEAR_USER_ACTION_MESSAGE';
